### ISSUE TITLE
Problema de compatibilidad con nueva version de monolog

### ISSUE THREAD

**Issue by RedGirasol** [APIHub-CdC/signature-manager-php#6]
apihub-cdc/signature-manager[1.0.0, ..., 1.0.1] require monolog/monolog ^1.24 -> found monolog/monolog[1.24.0, ..., 1.25.5] but the package is fixed to 2.1.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command

**Comment by macr243** [comment]
I'm agree with you, but the latest version we can update is 1.25.5 because the minimum required PHP version for us is 5, then monolog/monolog 2.1.1 requires as minimum PHP 7.2.
